"""add_highlights_to_analysis_items

Revision ID: bee2d1e57ac0
Revises: f9414530beec
Create Date: 2026-05-07 17:29:44.450013

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bee2d1e57ac0'
down_revision: str | None = 'f9414530beec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_items', sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_items', 'highlights')
    # ### end Alembic commands ###
